# This file is covered by the LICENSE file in the root of this project.
name: "kitti"
labels:
  0: "unlabeled"
  1: "outlier"
  10: "car"
  11: "bicycle"
  13: "bus"
  15: "motorcycle"
  16: "on-rails"
  18: "truck"
  20: "other-vehicle"
  30: "person"
  31: "bicyclist"
  32: "motorcyclist"
  40: "road"
  44: "parking"
  48: "sidewalk"
  49: "other-ground"
  50: "building"
  51: "fence"
  52: "other-structure"
  60: "lane-marking"
  70: "vegetation"
  71: "trunk"
  72: "terrain"
  80: "pole"
  81: "traffic-sign"
  99: "other-object"
  252: "moving-car"
  253: "moving-bicyclist"
  254: "moving-person"
  255: "moving-motorcyclist"
  256: "moving-on-rails"
  257: "moving-bus"
  258: "moving-truck"
  259: "moving-other-vehicle"
  301: "moveable-object"
  302: "on-road-object"
  303: "off-road-object"
color_map: # bgr
  0: [0, 0, 0]
  1: [0, 0, 255]
  10: [245, 150, 100]
  11: [245, 230, 100]
  13: [250, 80, 100]
  15: [150, 60, 30]
  16: [255, 0, 0]
  18: [180, 30, 80]
  20: [255, 0, 0]
  30: [30, 30, 255]
  31: [200, 40, 255]
  32: [90, 30, 150]
  40: [255, 0, 255]
  44: [255, 150, 255]
  48: [75, 0, 75]
  49: [75, 0, 175]
  50: [0, 200, 255]
  51: [50, 120, 255]
  52: [0, 150, 255]
  60: [170, 255, 150]
  70: [0, 175, 0]
  71: [0, 60, 135]
  72: [80, 240, 150]
  80: [150, 240, 255]
  81: [0, 0, 255]
  99: [255, 255, 50]
  252: [245, 150, 100]
  256: [255, 0, 0]
  253: [200, 40, 255]
  254: [30, 30, 255]
  255: [90, 30, 150]
  257: [250, 80, 100]
  258: [180, 30, 80]
  259: [255, 0, 0]
  301: [78, 121, 167]
  302: [89, 161, 79]
  303: [225, 87, 89]
content: # as a ratio with the total number of points
  301: 0.0476464607409658
  302: 0.361294395653881
  303: 0.591057682551199
# classes that are indistinguishable from single scan or inconsistent in
# ground truth are mapped to their closest equivalent 
learning_map:
  0: 2     # "unlabeled" mapped to "off-road-object" --------------mapped
  1: 2     # "outlier" mapped to "off-road-object" ----------------mapped
  10: 0    # "car" mapped to "moveable-object" --------------------mapped
  11: 0    # "bicycle" mapped to "moveable-object" ----------------mapped
  13: 0    # "bus"  mapped to "moveable-object" -------------------mapped
  15: 0    # "motorcycle" mapped to "moveable-object" -------------mapped
  16: 0    # "on-rails"  mapped to "moveable-object" --------------mapped
  18: 0    # "truck" mapped to "moveable-object" ------------------mapped
  20: 0    # "other-vehicle" mapped to "moveable-object" ----------mapped
  30: 0    # "person" mapped to "moveable-object" -----------------mapped
  31: 0    # "bicyclist" mapped to "moveable-object" --------------mapped
  32: 0    # "motorcyclist" mapped to "moveable-object" -----------mapped
  40: 1    # "road" mapped to "on-road-object" --------------------mapped
  44: 1    # "parking" mapped to "on-road-object" -----------------mapped
  48: 1    # "sidewalk" mapped to "on-road-object" ----------------mapped
  49: 1    # "other-ground" mapped to "on-road-object" ------------mapped
  50: 2    # "building" mapped to "off-road-object" ---------------mapped
  51: 2    # "fence" mapped to "off-road-object" ------------------mapped
  52: 2    # "other-structure"  mapped to "off-road-object" -------mapped
  60: 2    # "lane-marking"  mapped to "off-road-object" ----------mapped
  70: 2    # "vegetation" mapped to "off-road-object" -------------mapped
  71: 2    # "trunk" mapped to "off-road-object" ------------------mapped
  72: 2    # "terrain" mapped to "off-road-object" ----------------mapped
  80: 2    # "pole" mapped to "off-road-object" -------------------mapped
  81: 2    # "traffic-sign" mapped to "off-road-object" -----------mapped
  99: 2    # "other-object"  mapped to "off-road-object" ----------mapped
  252: 0   # "moving-car"  mapped to "moveable-object" ------------mapped
  253: 0   # "moving-bicyclist"  mapped to "moveable-object" ------mapped
  254: 0   # "moving-person"  mapped to "moveable-object" ---------mapped
  255: 0   # "moving-motorcyclist"  mapped to "moveable-object" ---mapped
  256: 0   # "moving-on-rails"  mapped to "moveable-object" -------mapped
  257: 0   # "moving-bus"  mapped to "moveable-object" ------------mapped
  258: 0   # "moving-truck"  mapped to "moveable-object" ----------mapped
  259: 0   # "moving-other-vehicle"  mapped to "moveable-object" --mapped
  301: 0   # "moveable-object"
  302: 1   # "on-road-object"
  303: 2   # "off-road-object"
learning_map_inv: # inverse of previous map
  0: 301     # "moveable-object"
  1: 302     # "on-road-object"
  2: 303     # "off-road-object"
learning_ignore: # Ignore classes
  0: False     # "moveable-object"
  1: False     # "on-road-object"
  2: False     # "off-road-object"
split: # sequence numbers
  train:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 9
    - 10
  valid:
    - 8
  test:
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
